# Base docker-compose file for aquarium
#
# Defines services for Aquarium, Krill, database, and S3.  Uses Docker network
# address translation, and containers for MySQL, and the Minio S3 server.
#
# Initializes the database the first time MySQL is run from the database dump
# in docker/mysql_init/dump.sql. If you want to use an alternative, replace this
# file.
#
# To reininitialize the database with the original or an alternative dump file,
# remove the docker/db directory with
#
#   sudo rm -rf docker/db/*
#
# before running `docker-compose up`

version: "3.5"
services:
  app:
    entrypoint: ["/aquarium/docker/aquarium-entrypoint-production.sh"]
    volumes:
      - ./db:/aquarium/db
      - ./log:/aquarium/log
    networks:
      - aquarium_net
    expose:
      - "3000"
    cap_add:
      - NET_ADMIN

  krill:
    entrypoint: ["/aquarium/docker/krill-entrypoint-production.sh"]
    networks:
      - aquarium_net
    expose:
      - "3500"
    depends_on:
      - app
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.route_localnet=1

  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    networks:
      - aquarium_net
    depends_on:
      - app

networks:
  aquarium_net:
