# Edit this file and copy it to config/database.yml

development:

  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

  production_server: # Listed here so that the development server can copy inventory db items from the production server

    adapter: mysql2
    encoding: utf8
    reconnect: true
    host: add host here
    port: 3306
    database: add db name here
    pool: 5
    username: add db username here
    password: "add db pass here"

test:

  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:

  adapter: mysql2
  encoding: utf8
  reconnect: true
  host: add host here
  port: 3306
  database: add db name here
  pool: 100
  username: add db username here
  password: "add db pass here"

rehearse:

  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: your.mysqlerver.com
  port: 3306
  database: rehearse
  pool: 100
  username: yourusername
  password: "yourpassword"

  production_server: # Listed so that the rehearsal server can copy inventory db items from the production server
    adapter: mysql2
    encoding: utf8
    reconnect: true
    host: add host here
    port: 3306
    database: add db name here
    pool: 5
    username: add db username here
    password: "add db pass here"
