# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:

  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

  production_server: # Listed so that the development server can copy inventory db items from the production server

    adapter: mysql2
    encoding: utf8
    reconnect: false
    host: istcsrv.cs.washington.edu
    port: 3306
    database: production
    pool: 5
    username: klavins
    password: "236236"

test:

  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:

  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: istcsrv.cs.washington.edu
  port: 3306
  database: production
  pool: 5
  username: klavins
  password: "236236"

rehearse:

  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: istcsrv.cs.washington.edu
  port: 3306
  database: rehearse
  pool: 5
  username: klavins
  password: "236236"

  production_server: # Listed so that the rehearsal server can copy inventory db items from the production server
    adapter: mysql2
    encoding: utf8
    reconnect: false
    host: istcsrv.cs.washington.edu
    port: 3306
    database: production
    pool: 5
    username: klavins
    password: "236236"
