title: Aquarium
description: The laboratory operating system
repository: https://github.com/klavinslab/aquarium
timezone: America/Los_Angeles
collections:
  docs:
    permalink: "/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: default
theme: jekyll-theme-cayman
show_releases: true
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text
baseurl: /aquarium
